# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [vendor]
# Site settings
title: Diney Wankhede
email: diney.12323@gmail.com 

description: > # this means to ignore newlines until "baseurl:"
  Learn more, see more.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://dineyw23.github.io" # the base hostname & protocol for your site
twitter_username: diney12323
github_username:  dineyw23

# Build settings
markdown: kramdown
